#**Numpy Array Operations**

**Problem Statement:** To learn how to use NumPy for creating arrays, performing basic array operations, and conducting numerical computations through analyzing temperature data.

**Scenario:** You are given a list of daily average temperatures (in degrees Celsius) recorded over two weeks. Your task is to use NumPy to analyze this data.

##1. Create a 1D NumPy Array:

In [3]:
import numpy as np

In [4]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]) #One Dimensional Array
print("Temprature in degrees Celsius :",temperatures_w1)

Temprature in degrees Celsius : [22.5 25.3 20.8 23.4 26.1 24.8 21.9]


##2. Inspection and Properties:

In [5]:
Shape_of_arr = temperatures_w1.shape
print("Shape of tempratures_w1 :",Shape_of_arr) #Shape

Dtype_arr = temperatures_w1.dtype
print("Data type of tempratures_w1 :",Dtype_arr) #Dtype

No_elem = temperatures_w1.ndim
print("Number of elements in tempratures_w1 :",No_elem) #No.of elements


Shape of tempratures_w1 : (7,)
Data type of tempratures_w1 : float64
Number of elements in tempratures_w1 : 1


##3. Array Operations:

In [6]:
#Convert the unit of Celsius to Fahrenheit
Fahrenheit = (temperatures_w1 * 9/5) + 32
print("Fahrenheit of tempratures_w1 :",Fahrenheit)

Fahrenheit of tempratures_w1 : [72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [7]:
#Maximum Temprature
temp_max = temperatures_w1.max()
print("Maximum Temprature :",temp_max)

#Minimum Temprature
temp_min = temperatures_w1.min()
print("Minimum Temprature :",temp_min)

#Mean of temprature
temp_mean = temperatures_w1.mean()
print("Mean of Temprature :",temp_mean)

Maximum Temprature : 26.1
Minimum Temprature : 20.8
Mean of Temprature : 23.542857142857144


##4. Array Slicing and Indexing:

In [8]:
# 1. Extract temperatures for the first three days (Mon, Tue, Wed)
first_three_days = temperatures_w1[:3]
print("First three days:\n", first_three_days)

# 2. Extract temperatures for the weekend (Sat, Sun)
weekend = temperatures_w1[-2:]
print("\nWeekend:\n", weekend)

# 3. Extract temperatures for the middle three days (Wed, Thu, Fri)
middle_three_days = temperatures_w1[2:5]
print("\nMiddle three days:\n", middle_three_days)


First three days:
 [22.5 25.3 20.8]

Weekend:
 [24.8 21.9]

Middle three days:
 [20.8 23.4 26.1]


##5. Create a 2D Array:

In [9]:
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],  # Week 1
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]   # Week 2
])

print("Temperature Data (2D Array):")
print(temperatures)

Temperature Data (2D Array):
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


##6. Inspect and Slice the 2D Array:

In [10]:
print("Shape of array:", temperatures.shape)      # Shape
print("Data type:", temperatures.dtype)           # Data type
print("Total number of elements:", temperatures.size)  # Total number of elements

Shape of array: (2, 7)
Data type: float64
Total number of elements: 14


In [11]:
week1 = temperatures[0]
print("\nWeek 1 Temperatures:\n", week1)
week2 = temperatures[1]
print("\nWeek 2 Temperatures:\n", week2)
weekend = temperatures[:, -2:]
print("\nWeekend Temperatures (Sat & Sun for both weeks):\n", weekend)


Week 1 Temperatures:
 [22.5 25.3 20.8 23.4 26.1 24.8 21.9]

Week 2 Temperatures:
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]

Weekend Temperatures (Sat & Sun for both weeks):
 [[24.8 21.9]
 [22.8 20.1]]


#**Pandas Series:**



##1. Creating Pandas Series:

In [13]:
import pandas as pd

In [14]:
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

# Display the Series
print("Marks Series:\n")
print(marks)

Marks Series:

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


##2. Indexing and Slicing:

In [16]:
# Use integer index position to access the mark of the 1st rank student
mark_first_rank = marks[0]
print("1. Mark of 1st Rank Student (by position):", mark_first_rank)

# Use loc to retrieve marks of top 3 ranks by index labels
top3_marks = marks.loc[['Rank1', 'Rank2', 'Rank3']]
print("\n2. Marks of Top 3 Ranks (using loc):\n", top3_marks)

# Use iloc to retrieve the mark of the 3rd rank student
mark_third_rank = marks.iloc[2]
print("\n3. Mark of 3rd Rank Student (using iloc):", mark_third_rank)

# Apply boolean mask to filter ranks with marks > 90
marks_above_90 = marks[marks > 90]
print("\n4. Ranks with Marks > 90:\n", marks_above_90)

1. Mark of 1st Rank Student (by position): 95

2. Marks of Top 3 Ranks (using loc):
 Rank1    95
Rank2    92
Rank3    89
dtype: int64

3. Mark of 3rd Rank Student (using iloc): 89

4. Ranks with Marks > 90:
 Rank1    95
Rank2    92
dtype: int64


/tmp/ipython-input-339802012.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  mark_first_rank = marks[0]


##3. Manipulating Series:

In [17]:
# Modify the mark of the student with the 1st rank to 100
marks['Rank1'] = 100
print("1. Updated Marks (Rank1 modified to 100):\n", marks)

# Remove the entry corresponding to the last rank
marks = marks.drop('Rank5')
print("\n2. Series after removing last rank:\n", marks)

# Compute CGPA by dividing each mark by 10
cgpa = marks / 10
print("\n3. CGPA (Marks ÷ 10):\n", cgpa)

1. Updated Marks (Rank1 modified to 100):
 Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

2. Series after removing last rank:
 Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

3. CGPA (Marks ÷ 10):
 Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


#**Pandas DataFrame:**

##1. Creating Pandas DataFrame:

In [18]:
# Create the DataFrame
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
                        'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

# Display the DataFrame
print("Transactions DataFrame:\n")
print(transactions)

Transactions DataFrame:

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


##2. Data Exploration:

In [19]:
# 1 Display DataFrame and its basic info
print("Transactions DataFrame:\n", transactions)
print("\nHead (first 5 rows):\n", transactions.head())
print("\nTail (last 5 rows):\n", transactions.tail())
print("\nShape of DataFrame:", transactions.shape)
print("\nColumn Names:", transactions.columns.tolist())
print("\nData Types:\n", transactions.dtypes)

# 2 Display only 'ProductCategory' and 'Amount' columns
print("\nSelected Columns (ProductCategory & Amount):\n", transactions[['ProductCategory', 'Amount']])

# 3 Retrieve the last 3 columns using iloc
print("\nLast 3 Columns using iloc:\n", transactions.iloc[:, -3:])

# 4 Filter rows where Region is 'North' and Amount > 200
north_high = transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]
print("\nFiltered Rows (Region='North' & Amount>200):\n", north_high)

# 5 Find value counts for ProductCategory
print("\nValue Counts for ProductCategory:\n", transactions['ProductCategory'].value_counts())

# 6 Find unique values in Region column
print("\nUnique Regions:\n", transactions['Region'].unique())

# 7 Group by Region and find mean Amount
print("\nMean Amount by Region:\n", transactions.groupby('Region')['Amount'].mean())

Transactions DataFrame:
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Head (first 5 rows):
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Tail (last 5 rows):
    TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107  

##3. Manipulating the DataFrame:

In [20]:
# 1 Modify 'Amount' for TransactionID 102 to 165
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
print("1. Updated Amount for TransactionID 102:\n", transactions, "\n")

# 2 Add a new column 'Discount' = 10% of Amount
transactions['Discount'] = transactions['Amount'] * 0.10
print("2. Added 'Discount' column (10% of Amount):\n", transactions, "\n")

# 3 Remove the row with TransactionID 109
transactions = transactions[transactions['TransactionID'] != 109]
print("3. Removed row with TransactionID 109:\n", transactions, "\n")

# 4 Delete the 'Discount' column
transactions = transactions.drop(columns=['Discount'])
print("4. Deleted 'Discount' column:\n", transactions)

1. Updated Amount for TransactionID 102:
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400 

2. Added 'Discount' column (10% of Amount):
    TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  N

#End
--